# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cm662xl0k-capi-aws
  namespace: cm662xl0k
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cm662xl0k-capi-aws
subjects:
- kind: ServiceAccount
  name: cm662xl0k-capi-aws
